apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ek9tm3twy-nodejs 
  janus-idp.io/tekton: ek9tm3twy-nodejs
  backstage.io/kubernetes-id: ek9tm3twy-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ek9tm3twy-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml