apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ek9tm3twy-nodejs
  janus-idp.io/tekton: ek9tm3twy-nodejs
  backstage.io/kubernetes-id: ek9tm3twy-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ek9tm3twy-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
